name: CHECK_PACKAGE_VERSION_BEFORE_UPDATE_MAIN
on:
  push:
    branches:
      - main # Dispara el workflow cuando se hace push a la rama 'main'
  pull_request:
    branches:
      - main # Dispara el workflow cuando se abre/actualiza un Pull Request hacia 'main'

jobs:
  release:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      # Use this GitHub Action
      - name: Check package version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          PUBLISHED_VERSION=$(npm view "$PACKAGE_NAME" version)

          echo "Current version in package.json: $CURRENT_VERSION"
          echo "Latest published version in NPM: $PUBLISHED_VERSION"

          if npx semver "$CURRENT_VERSION" -le "$PUBLISHED_VERSION"; then
            echo "❌ Error: Version must be greater than published version"
            exit 1
          fi